### PR TITLE
lib support for FASTLOG_LEVEL

### PR DESCRIPTION
**Pull request by sumarlidason**
brings `FASTLOG_LEVEL` env variable into the forefront of the upfront!

### CODE REVIEW

**Comment by sumarlidason** [comment]
🍰 This PR also updates travis, all depends, and tests.

**Comment by sumarlidason** [comment]
cc @willwhite

**Comment by willwhite** [comment]
Hi @sumarlidason. This module doesn’t currently have an interface with environment variables and it might be cleaner to keeping it that way. Are you able to read the environment variable upstream in your application and then pass the result into fastlog like you normally would?

**Comment by sumarlidason** [comment]
can't remember any of this, closing.

**Pull request closed without merging**
